### ISSUE TITLE
Transfer Ownership to pgRouting?

### ISSUE THREAD

**Issue by dkastl** [pgRouting/gtfs2pgrouting#2]
@justjkk, would you mind to transfer ownership of the gtfs2pgrouting repository to the pgRouting organization?

According to @cvvergara it often causes troubles, if we are doing the main development in a forked repository, because pull requests tend to go by default to the main one.

**Comment by justjkk** [comment]
This is done now. Sorry it took a while to check my notifications.

**Comment by dkastl** [comment]
Thank you!
